package enums;

public enum ConversationState {
    CONVERSATION_STARTED,
    WAITING_FOR_CHOISE,
    WAITING_FOR_SETTING,
    GETTING_CURRENCY,
    WAITING_FOR_FORMAT,
    WAITING_FOR_BANK,
    WAITING_FOR_CURRENCY,
    WAITING_FOR_MESSAGES,
    GETTING_BANK

}
