package enums;

public enum ConversationState {
    CONVERSATION_STARTED,
    WAITING_FOR_CHOISE,
    WAITING_FOR_SETTING,
    GETTING_CURRENCY,
    GETTING_BANK,
    GETTING_FORMAT,
    GETTING_REMINDER,
    FROM_REMiNDER,
    WAITING_FOR_BANK,
    WAITING_FOR_CURRENCY,
    WAITING_FOR_MESSAGES

}
